### PR TITLE
chore: Update cmdk to 1.0.0, add simple filter for Command components for better ranking, address an issue with cmdk 1.0.0 regarding disabled items in dropdown

### PR DESCRIPTION
**Pull request by SamZhang02**

### CODE REVIEW

**Comment by SamZhang02** [comment]
@itsjoeoui do you mind trying out on your side this one specific thing when you have time: 
In the `select currency` dropdown, the typing in the first and second letter has a little bit of lag on my side due to the filter thing; it's not THAT noticeable for me tho so I wanted to see your opinion. It's most likely the `toLowercase()` being slow

**Comment by itsjoeoui** [comment]
still on vacation haha, will review this when I get back 💯

**Comment by SamZhang02** [comment]
dw bro enjoy the foooooods

**Comment by itsjoeoui** [comment]
Included in #63 🚀

**Pull request closed without merging**
